FROM docker.io/rocm/pytorch:latest

LABEL org.opencontainers.image.authors="flowpoint@protonmail.com"

ENV HF_HOME=/root/.cache/huggingface

RUN apt update && apt-get install -y \
    python3-dev \
    tmux \
    vim

RUN pip install pipenv
