logdir: "/tmp/output"
checkpoint_dir: "./output"

name: 'hypersearch_full_2'
seed: 42
hostname: localhost
port: 12355
max_checkpoints: 3

num_gpus: 'auto'
precision: mixed
cuda_graphs: False

preprocess_cores: 10
preprocess_mode: concat
max_input_tokens: 256
languages:
  - python

epochs: 2
shards: 8
warmup_batches: 10000

finetune_mode: all

model_name: 'microsoft/codebert-base'
optimizer: adam
lr_schedule: constant

learning_rate: 1e-5
batch_size: 8
grad_accum: 64 # counted in batches
temp: 0.05
dropout: 0.1

embedding_size: 128
top_k:  10
